CREATE TABLE payables
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    due_date     TIMESTAMP WITHOUT TIME ZONE,
    payment_date TIMESTAMP WITHOUT TIME ZONE,
    value        DECIMAL,
    description  VARCHAR(255),
    status       VARCHAR(255)
);